# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedmp < Formula
  desc ""
  homepage "https://github.com/shundezhang/homebrew-kubedmp"
  version "0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.2/kubedmp_0.2_darwin-arm64.tar.gz"
      sha256 "52993324e47fa22f7cc4cdb771c2e266884e251721fb863a18807907f0e3062f"

      def install
        bin.install "kubedmp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.2/kubedmp_0.2_darwin-amd64.tar.gz"
      sha256 "180cee51714a7591c273e66b1996d57f5e0023743cf74441c6955c8cecbf50e1"

      def install
        bin.install "kubedmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.2/kubedmp_0.2_linux-amd64.tar.gz"
      sha256 "92dd076b8b63f9d7d67942c9be31d852d7d16814d061c8ad836dbaae917c462a"

      def install
        bin.install "kubedmp"
      end
    end
  end
end
