# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedmp < Formula
  desc ""
  homepage "https://github.com/shundezhang/homebrew-kubedmp"
  version "0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.8/kubedmp_0.8_darwin-arm64.tar.gz"
      sha256 "e6165447e603b531ce5f2f27e94697bd20fbe61e29fd8c957d11945de557fbc9"

      def install
        bin.install "kubedmp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.8/kubedmp_0.8_darwin-amd64.tar.gz"
      sha256 "78d3cc2e4f45cc30fcaef440e70dd3ee16994cfd16ba81cd4849eccebba380ba"

      def install
        bin.install "kubedmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shundezhang/kubedmp/releases/download/0.8/kubedmp_0.8_linux-amd64.tar.gz"
      sha256 "8cd3ae51dbe334bc60f6e8761a07460b7ea8163eaa01b29ae8e1c05856294289"

      def install
        bin.install "kubedmp"
      end
    end
  end
end
